### ISSUE TITLE
Middle-clicking sorts, but doesn't update the visuals

### ISSUE THREAD

**Issue by magneticflux-** [kyrptonaught/Inventory-Sorter#10]
Sorting with the button sorts and correctly updates the items visually, but middle-click sorting (which I got into the habit of doing from InventoryTweaks years ago) only sorts the items "internally", with no visual change.

I'm not sure how this can happen since both methods just call `sendSortPacket` but it somehow does.

**Comment by kyrptonaught** [comment]
Do you have middle click bound to anything else?

**Comment by magneticflux-** [comment]
Pick Block, by default. I cloned the repo and the same thing happens in the dev env, no other mods.

**Comment by kyrptonaught** [comment]
If you unbind that does the issue persist?

**Comment by magneticflux-** [comment]
Yes the issue goes away when pick block is unbound.
