### ISSUE TITLE
Crashing on 1.20.2 and Feature Suggestion

### ISSUE THREAD

**Issue by ual1n** [kyrptonaught/Inventory-Sorter#109]
The mod for 1.20.1 is being loaded in 1.20.2, however, when opening a chest the game crashes.

In addition, I would like to suggest some additions for the next updates. Just like the Quark mod, it would be interesting to have more than one button to filter items, not just one, so the player could filter, for example, by name, type, category or item ID.
![seed-pouch](https://github.com/kyrptonaught/Inventory-Sorter/assets/131735376/aea41800-5e98-4741-b6f1-8ecbc4af666d)

**Comment by vico93** [comment]
See my comment in #110
