### ISSUE TITLE
Sorting doubles item stacks when in Creative mode

### ISSUE THREAD

**Issue by magneticflux-** [kyrptonaught/Inventory-Sorter#11]
I can't replicate it in survival, but it probably shouldn't happen at all, regardless of gamemode.

To reproduce, move an item directly down in your inventory and sort it. Sometimes it gets duped.

**Comment by kyrptonaught** [comment]
Does this happen when sorting using the button and not the keybinding/middle click?

**Comment by magneticflux-** [comment]
The button and the key/mouse binding cause it to happen.

**Comment by kyrptonaught** [comment]
Creative inventory or all inventories?

**Comment by magneticflux-** [comment]
Only the Creative inventory.

**Comment by kyrptonaught** [comment]
The player inventory section of the creative inventory is a bit wonky when it comes to things like this, might have to set up a separate sorting condition for it. I’ll look into it, thank you for the bug report
