### ISSUE TITLE
Crash when opening creative inventory

### ISSUE THREAD

**Issue by Eliteneet** [kyrptonaught/Inventory-Sorter#13]
I'm having a problem with opening the creative menu with just this mod installed. I haven't seen anyone else report this.

Fabric Loader 0.6.2 Build 166
Fabric Api 0.3.3 Build 234
Inventory Sorter 1.5.7

Crashlog:
[https://pastebin.com/PeWWPZXp](url)

**Comment by fatlard1993** [comment]
I am also seeing this. It happens with "display button in inventory" set to "no". If set to "yes" it does not crash.

**Comment by kyrptonaught** [comment]
This has been fixed in 1.6.3, I apologize for the delay
