### ISSUE TITLE
[1.15pre] mb3 sorting messes with the vanilla "pickitem" functionality in creative, overriding it

### ISSUE THREAD

**Issue by Yoghurt4C** [kyrptonaught/Inventory-Sorter#14]
how to replicate:
-get inventorysorting
-put a single item in your inventory slot
-middleclick on it

**Comment by kyrptonaught** [comment]
Does this still occur if you rebind the key to something else?

**Comment by Yoghurt4C** [comment]
no, but:
-inventorysorting is hardcoded to mb3
-rebinding a vanilla keybind because of this is silly
-other sorting mods seem to have no problems with this

maybe this could be resolved by not allowing inventorysorter to sort when it's activated while the cursor is aiming at an item while in creative?

**Comment by kyrptonaught** [comment]
The middle click sort cannot be rebound, but it can be disabled. But I do agree that it is silly, I always rebind my pick block key to something else so this completely slipped past me in testing. I'll look into a fix

**Comment by magneticflux-** [comment]
This also occurs in survival mode. Picked blocks that exist in your inventory are moved to your hotbar if you're looking at something while sorting.
