### ISSUE TITLE
[20w10a - 20w11a] Crashes at start

### ISSUE THREAD

**Issue by Ectalite** [kyrptonaught/Inventory-Sorter#16]
Crashes with latest snapshot (and 20w10a) and latest version of fabric api for this snapshot. 
https://pastebin.com/7buxVNwf

**Comment by 3Domse3** [comment]
Same for me

**Comment by kyrptonaught** [comment]
It has not been updated for the snapshots yet, I will look into updating all my projects over the weekend

**Comment by Ectalite** [comment]
Ok thank you 

14 mars 2020 à 00:22 de notifications@github.com:

**Comment by Minepig** [comment]
it also crashes on 20w14a
