### ISSUE TITLE
Question about changing configs

### ISSUE THREAD

**Issue by domek16** [kyrptonaught/Inventory-Sorter#18]
Hello, I just installed last version for 1.15.2 Fabric, everything is working fine but i don't know how to change config(sort by category etc)

**Comment by kyrptonaught** [comment]
Did you install the mod menu mod? One of the things mod menu does is allow you to edit configs in game

**Comment by domek16** [comment]
Yes, I did install that but I didn't know that there is config editing option. Thanks, I'll check that. Have a great day!
