### ISSUE TITLE
Request: Change sort order of incomplete stacks

### ISSUE THREAD

**Issue by calloatti** [kyrptonaught/Inventory-Sorter#2]
Just a little minor detail, but my OCD level peaks with this one.

Can the sort order of incomplete stacks be changed from this: (8,64,64,64, 17,64,64)

![image](https://user-images.githubusercontent.com/12817862/61585115-b8dd5580-ab2a-11e9-9027-ea90820f0ad7.png)

To this: (64,64,64,8, 64,64,17)

![image](https://user-images.githubusercontent.com/12817862/61585116-bed33680-ab2a-11e9-8f63-79ffd76c73b5.png)

**Comment by kyrptonaught** [comment]
Fixed as of 1.3.0
