### ISSUE TITLE
Crash when combined with REI and Spinnery

### ISSUE THREAD

**Issue by sschr15** [kyrptonaught/Inventory-Sorter#25]
Spinnery adds a way to create a crafting recipe in-game, however for some reason Minecraft's slot handler considers there to be no slots after opening and closing an REI window. Due to your hardcoded `size - 36` and lack of a `Math.min()`, the game crashes at this point, and Not Enough Crashes blames the other two mods.

I was "thinking out loud" on a Java discord server about the problem as I was working through it. I also [have a crash report](https://gist.github.com/sschr15/124f64371e209bd5f4cdb92f58a61ae7) if you need/want.
![discussion with myself of the problem](https://user-images.githubusercontent.com/15277819/89248020-41168780-d5d4-11ea-881f-1c996dcf6240.png)

**Comment by kyrptonaught** [comment]
I really dislike how much spinnery nukes vanilla functionality, but anywho can you verify if this fixes the crash?
[InventorySorter-1.7.1-1.16.zip](https://github.com/kyrptonaught/Inventory-Sorter/files/5020035/InventorySorter-1.7.1-1.16.zip)

**Comment by sschr15** [comment]
That fixes the problem, with the slight problem of setting one icon on top of the other:
![image](https://user-images.githubusercontent.com/15277819/89314857-cd11c900-d63f-11ea-94b2-92cd7ab2f591.png)
Otherwise, it fixed the problem!

**Comment by shedaniel** [comment]
when will the build be released

**Comment by kyrptonaught** [comment]
Oops, forget to comment here, it's up on curseforge now
