### ISSUE TITLE
[feature request] sort books/gear by enchantment

### ISSUE THREAD

**Issue by rmobis** [kyrptonaught/Inventory-Sorter#27]
I'm wondering if you'd be interested in implementing sorting by enchantment. This would be specially awesome when sorting chests of enchanted books, but could also be useful for enchanted gear.

If that's a feature you'd approve, **I'm willing to work on a PR**. Just let me know.

**Comment by kyrptonaught** [comment]
Sounds pretty useful to me, feel free to if you've got the time, if not I could.

**Comment by kyrptonaught** [comment]
This is where you'd want to look https://github.com/kyrptonaught/Inventory-Sorter/blob/master/src/main/java/net/kyrptonaught/inventorysorter/SortCases.java

**Comment by rmobis** [comment]
Ok, so I started messing around with the code and I realized sorting enchanted books **should** already be working, but for some reason it isn't. So I opened #28 to solve that first.
