### ISSUE TITLE
Display 'Sort' button on left broken in InventorySorter-1.4.0.jar

### ISSUE THREAD

**Issue by calloatti** [kyrptonaught/Inventory-Sorter#3]
MC 1.14.3
InventorySorter-1.4.0.jar

I had `Display 'Sort' button on left` set to Yes before updating to InventorySorter-1.4.0.jar.

After updating to InventorySorter-1.4.0.jar, the sort button is always on the right, the config screen is set to yes, but the config file value is set to false.

I had to edit the config file and change `"left_display": true` to make it work. Changing the setting in the config screen in game does nothing, and its always set to "Yes"

**Comment by kyrptonaught** [comment]
No longer relevant in 1.5.0
