### ISSUE TITLE
Having this mod on the client crashes the client when clicking on an AE2 autocraft recipe.

### ISSUE THREAD

**Issue by ProsperCraft** [kyrptonaught/Inventory-Sorter#35]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4639
It is sad they didn't report this to you, I found it there, and it is exactly what I am having.

Log-
https://gist.github.com/ProsperCraft/bdb4b565b497480e456a104b8b3780d6
Crash log-
https://gist.github.com/ProsperCraft/1bf692a2c9bf725e67f1601f01142367

Removing Inventory Sorter stops the client crash.

**Comment by justastranger** [comment]
Can confirm, crashes for me as well and resolves as soon as this mod is removed. Really sad, since I really prefer using this inventory sorting mod.

**Comment by kyrptonaught** [comment]
Wow I apologize for the delay, but this has now been fixed
