### ISSUE TITLE
Unable to sort chests

### ISSUE THREAD

**Issue by magneticflux-** [kyrptonaught/Inventory-Sorter#37]
After 2aec6579a18e7a07f6b3302d2e0fb383d2fa39f3, I can't sort any chests. Only player inventory sorting works.

**Comment by Romz24** [comment]
I confirm, it doesn't work for me either.

**Comment by kyrptonaught** [comment]
Hmm odd, it worked fine in dev, but can confirm it isn't working in real use. Investigating

**Comment by kyrptonaught** [comment]
Should be fixed in 1.7.6
