### ISSUE TITLE
Question about blacklist.json5

### ISSUE THREAD

**Issue by alexei-vedder** [kyrptonaught/Inventory-Sorter#39]
Hello! Could you please help with configuring blacklist.json5 file? I don't want enchanted books to be sorted, so I added in blacklist.json5 the id of this item "minecraft:enchanted_book":
```
{
    "blacklistedInventories": [
        "minecraft:enchanted_book"
    ]
}
```
but those are still sorted. How to properly configure this file?

**Comment by kyrptonaught** [comment]
This blacklist is for blacklisting inventories from being sorted, not for items. That would be a good feature to add though

**Comment by alexei-vedder** [comment]
So if I wrote for example
```
{
    "blacklistedInventories": [
        "minecraft:chest"
    ]
}
```
then all chests won't be sorted, but shulkerboxes, barrels, etc are still sortable, am I right?

**Comment by kyrptonaught** [comment]
Unfortunately it doesn't work per block, it uses the internal name for the screen. A lot of blocks re use the same screen for their inventories.

Chests and barrels use:
net.minecraft.client.gui.screen.ingame.GenericContainerScreen
Shulkers use:
net.minecraft.client.gui.screen.ingame.ShulkerBoxScreen

**Comment by alexei-vedder** [comment]
It seems my problem can be resolved by adding to the blacklist the Shulkerbox screen and place there items I don't want to be sorted. Thanks!
