### ISSUE TITLE
[Suggestion] Change "Sort By" by scrolling mouse wheel up/down

### ISSUE THREAD

**Issue by goldern** [kyrptonaught/Inventory-Sorter#40]
As stated, it would be awesome if you could use the mouse wheel to change the "Sort By" from NAME to CATEGORY, MOD or ID by scrolling the mouse wheel while hovering the icon
![image](https://user-images.githubusercontent.com/5741155/108005152-ab25d580-6fd6-11eb-88f7-dd74bcf75eaa.png)

**Comment by kyrptonaught** [comment]
This has been implemented in 1.7.7
