### ISSUE TITLE
/sort command is missin

### ISSUE THREAD

**Issue by tyleraharrison** [kyrptonaught/Inventory-Sorter#42]
In the CurseForge comments you said there was a /sort command. This seems to be missing on the server-side. Does this only work if the client has this installed? If so, I think this should be fairly easy to implement on only the server.

**Comment by kyrptonaught** [comment]
Ah yeah this was broken at some point, thanks for noticing. Fixed in 1.7.8

**Comment by tyleraharrison** [comment]
Can confirm both commands work when mod is installed to server, does not need to be installed for the client. Great work @kyrptonaught!
