### ISSUE TITLE
Middle Clicking Inventory While Chest Is Open Sorts Chest

### ISSUE THREAD

**Issue by nymphlode** [kyrptonaught/Inventory-Sorter#45]
I'm running into an issue where I middle click my own inventory while a chest is open and it sorts the chest instead of my inventory.

Steps to reproduce:
1. Open chest
2. Middle-click on your own inventory.
3. The chest will sort instead of your inventory

GIF attached for reference:
![inventorysorterbugreporrt](https://user-images.githubusercontent.com/11083026/114326885-a9b2ee00-9aeb-11eb-9562-81b459993bed.gif)

**Comment by kyrptonaught** [comment]
Seems like it isn't checking to verify where your mouse curser was when you're middling clicking and just defaulting to the other inv. I'll investigate

**Comment by kyrptonaught** [comment]
This has been fixed in 1.7.9, via an enabled by default config option
