### ISSUE TITLE
Default screen blacklist is not applied on new install

### ISSUE THREAD

**Issue by deirn** [kyrptonaught/Inventory-Sorter#47]
In [IgnoreList.java](https://github.com/kyrptonaught/Inventory-Sorter/blob/master/src/main/java/net/kyrptonaught/inventorysorter/client/config/IgnoreList.java) appears that you wanted to add a default blacklist of troublesome containers, but it's not being applied on new install

**Comment by kyrptonaught** [comment]
They all do get referenced, the list that it's in will prevent its inventory from being sorted, not the players too. It should then be moved to the ignoreList. Which will prevent both inventories. Sorry I'm on mobile 

See https://github.com/kyrptonaught/Inventory-Sorter/blob/master/src/main/java/net/kyrptonaught/inventorysorter/InventoryHelper.java line 65.

And https://github.com/kyrptonaught/Inventory-Sorter/blob/master/src/main/java/net/kyrptonaught/inventorysorter/mixin/MixinContainerScreen.java line 52

**Comment by deirn** [comment]
oh sorry, I'm a little confused since the json file doesn't get filled
