### ISSUE TITLE
dependency issues?

### ISSUE THREAD

**Issue by oliwoli** [kyrptonaught/Inventory-Sorter#48]
Building fails with the following error:

A problem occurred configuring root project 'Inventory-Sorter'.
> Could not resolve all files for configuration ':modImplementation'.
   > Could not resolve net.kyrptonaught:kyrptconfig:1.1.6-1.16.
     Required by:
         project :
      > Could not resolve net.kyrptonaught:kyrptconfig:1.1.6-1.16.
         > Could not get resource 'https://dl.bintray.com/kyrptonaught/kyrptconfig/net/kyrptonaught/kyrptconfig/1.1.6-1.16/kyrptconfig-1.1.6-1.16.pom'.
            > Could not GET 'https://dl.bintray.com/kyrptonaught/kyrptconfig/net/kyrptonaught/kyrptconfig/1.1.6-1.16/kyrptconfig-1.1.6-1.16.pom'. Received status code 403 from server: Forbidden

**Comment by kyrptonaught** [comment]
Ah this is due to bintray EOL. They claimed it would continue to be read only, but it doesn't seem that way

**Comment by oliwoli** [comment]
I see. Maybe you should use jitpack instead?

**Comment by kyrptonaught** [comment]
This has been fixed in the 1.17 version. I'll backport it too
