### ISSUE TITLE
Server crash on sort

### ISSUE THREAD

**Issue by nataliejean2412** [kyrptonaught/Inventory-Sorter#5]
My server is crashing whenever any of my players try to sort anything (inventory, chests, etc). I have a crash log, but I'm not entirely sure what is happening. It happens both with the middle mouse wheel and key shortcut, as well as the GUI button.

[crash-2019-07-28_20.17.02-server.txt](https://github.com/kyrptonaught/Inventory-Sorter/files/3439720/crash-2019-07-28_20.17.02-server.txt)

Minecraft Server v1.14.4
Mod Files used:

```
Adorn-1.2.0+1.14.4.jar
appleskin-mc1.14-fabric-1.0.6.jar
Autofish-0.8.4-fabric-mc1.14.jar
chunk-activator-1.2.0+mc1.14.4.jar
durabilityviewer-1.14-fabric0.2.7-1.5.jar
easyexcavate-1.5.1.jar
ender_compass-2.2.1.jar
fabric-api-0.3.0+build.206.jar
fabric-language-kotlin-1.3.40+build.1.jar
FabricMagnet-1.14-1.0.1.jar
fabricmod_VoxelMap-1.9.13_for_1.14.4.jar
FenceJumper-1.14.2-1.0.7.jar
fishtraps-0.0.4.jar
Harvest-1.14-fabric-1.0.4.jar
InventorySorter-1.4.2.jar
leaf-decay-1.0.3.jar
malilib-fabric-1.14.4-0.10.0-dev.20.jar
notenoughwands-1.14-1.7.5.beta.jar
RoughlyEnoughItems-2.9.7+build.143.jar
simpleteleporters-FABRIC-1.14.1-1.1.0.jar
stockpile-1.0.9+1.14.4.jar
theoneprobe-1.14-1.4.29.beta.jar
vanilla-hammers-1.5.0.jar
vanilladeathchest-1.14.3-1.10.1.0-fabric.jar
vivatech-1.0.0-alpha.14+1.14.4.jar
woodmill-1.1.0.jar

```

**Comment by kyrptonaught** [comment]
Oh no! I apologize, I think I know the issue. Accidentally moved some client side code to run on the server as well. I’ll have a fix shortly

**Comment by nataliejean2412** [comment]
See, that's what had me confused. I was seeing client calls in the server console and thought I was going crazy.

**Comment by kyrptonaught** [comment]
Does this fix it? 
[InventorySorter-1.4.3.jar.zip](https://github.com/kyrptonaught/Inventory-Sorter/files/3439833/InventorySorter-1.4.3.jar.zip)

**Comment by nataliejean2412** [comment]
Nope. Still crashing.

[crash-2019-07-28_21.34.09-server.txt](https://github.com/kyrptonaught/Inventory-Sorter/files/3439842/crash-2019-07-28_21.34.09-server.txt)

**Comment by kyrptonaught** [comment]
Similar issue, different spot. 
[InventorySorter-1.4.3.zip](https://github.com/kyrptonaught/Inventory-Sorter/files/3439889/InventorySorter-1.4.3.zip)

**Comment by nataliejean2412** [comment]
Confidence rewarded. That did the trick! Thank you so much!

**Comment by kyrptonaught** [comment]
No problem! If anything else comes up don't be afraid to ask
