### ISSUE TITLE
Port inventory sorting functionality from Inventory Profiles

### ISSUE THREAD

**Issue by NebelNidas** [kyrptonaught/Inventory-Sorter#51]
It seems like [Inventory Profiles](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles) has been abandoned, which is a shame, because it had the best inventory sorting functionality for fabric out there (works the same as Inventory Tweaks did).

This would
1. Improve the current UI,
2. Add more sorting styles (horizontal and vertical) and
3. Add client-side only sorting (thus fixing #19)!

**Comment by frozenwarrior41** [comment]
this is something that i can back up, while i enjoy the mod and it will suffice and it will help inventory management, inventory profiles was much more beneficial in what it could do

**Comment by kyrptonaught** [comment]
I would prefer to keep this server-sided. But it's probably about time I do something about client side sorting. Maybe an optional function that would be enabled if the mod is not installed on the server.

**Comment by NebelNidas** [comment]
> But it's probably about time I do something about client side sorting

Would be appreciated, yes! Although in the meantime Inventory Profiles has been [forked and updated to 1.17](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next) by a different developer, so it's no longer **that** necessary.

In my opinion, it would be best if efforts could be merged to get a solution which uses Inventory Profile's client-side sorting by default, but, if the server also has the sorting mod installed, it usesto that 🤔

**Comment by meza** [comment]
Client-only mode has been implemented with version 3.0.0
