### ISSUE TITLE
Sort on double click without client mod

### ISSUE THREAD

**Issue by skerit** [kyrptonaught/Inventory-Sorter#55]
On my Paper servers I had a server-side sorting plugin which allowed you to sort your chests by double clicking an empty slot. Players loved it, and ever since switching to Fabric I still get asked the question when it will return.

I've installed your mod on my Fabric server, and it runs great. But most people don't want to mess around with installing Fabric and such just to sort their chests. And typing the command each time is too much work.

So can it be implemented so that players without the mod can sort their chests by just double clicking an empty inventory slot?

**Comment by kyrptonaught** [comment]
Hm, I did implement this and get it working. But then I realized that the client is determining if the current open inventory is sortable, not the server. So it's gonna be a bit more work to get this migrated to server side, and most likely not be compatible with older versions(and the saved config).

**Comment by kyrptonaught** [comment]
I forgot to mention that this was added in 1.8.0
