### ISSUE TITLE
[SUGGESTION] Have the Server control the Inventory Screen Blacklist.

### ISSUE THREAD

**Issue by dandin87** [kyrptonaught/Inventory-Sorter#56]
I'm pretty sure I've talked to you on discord, as I thought I had made an issue previously but see that I never made one. What I do recall is that you said the server doesn't use the config, and that only the client does. At least this is my memory lol. 

Anyways, the reason I want the server to control the Blacklist is because, for example, Adorn Trading Tables can have their buy/sell items swapped, and Danks can end up removing everything above the vanilla stack limit. For AoF3 we did ship a client config with the screens we wanted disabled, and that worked, but then the config ended up default with the last update, and players can once again swap the buy/sell. But even with them having the config we ship, nothing is preventing them from removing those blacklisted inventories themselves to grief/steal.

**Comment by kyrptonaught** [comment]
You are correct in that the server really doesn't touch the config, it does have too much trust in the client. 

I would like to switch the blacklisting to the server, it would solve a lot of issues. I'll do some research, but I'm not sure if the screens are as easily identifiable on the server as they are on the client. This config would also need to be synced to the client as well to prevent the button from displaying

**Comment by kyrptonaught** [comment]
Forgot to mention that this was added in 1.8.0
