### ISSUE TITLE
i dont know, Minecraft just dont want see this mod

### ISSUE THREAD

**Issue by Pleyho** [kyrptonaught/Inventory-Sorter#58]
[https://ibb.co/F6zFTjT](url)

**Comment by RDKRACZ** [comment]
You are... running Forge. What did you expect to happen?

**Comment by Pleyho** [comment]
Hi,
Yes I'm running Forge obviously.
I don't know if you saw the screenshots that I added to GitHub,

In the first picture the number of mods on the folder (13) and Minecraft
(12) don't combine. Actually u can see the Minecraft and Forge version.

In the second picture I try to run the game using only fabric api and
Inventory Sorter but I have the same problem... Minecraft doesn't read the
mod or don't see it... I don't know.

In the last picture I sort mods in alphabetical order, doing that
the "InventorySorter" position will be below "Gravestone Mod" but it's
missing.

I await your answer.

**Comment by seeruk** [comment]
This is not a Forge mod, it's a Fabric mod. Putting Fabric API in your mods folder doesn't mean you're using Fabric - you need to actually use the Fabric mod loader, as in _instead of_ Forge. Fabric and Forge are both mod loaders, you can only use one or the other. 

Head over here to set up Fabric: https://fabricmc.net/use/
