### ISSUE TITLE
Blacklisting requires a tutorial

### ISSUE THREAD

**Issue by Sang-bin** [kyrptonaught/Inventory-Sorter#62]
The sort button is in a strange place in certain modes.
So I tried to delete it through settings, but there was no way to use it.
How to set up a blacklist A detailed method is needed.

Please add an easy-to-use method (eg mod name) or a way to find it.

**Comment by kyrptonaught** [comment]
In 1.8.2, I have added the ability to do this ingame. Hold left control and click on the sort button displayed in the inv.
