### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'kyrptconfig'!

### ISSUE THREAD

**Issue by TheRanker** [kyrptonaught/Inventory-Sorter#65]
https://pastebin.ubuntu.com/p/WBVpJG4wH9/
is the crash log of the modpack im developing .. while using the lastest version 
InventorySorter-1.8.2-1.18.jar
fabric 0.12.12

total of 275 mods included. 

just updated inv sorter today, crashed.. reverted, works fine. 

need any additoinal info, just ask :)

**Comment by TheRanker** [comment]
i never tried to reset the config.. will do that now

**Comment by kyrptonaught** [comment]
I think I know exactly what's causing this. Doesn't appear to be an issue with inventory sorter, but rather my config library that I bundle with my mods. I'm assuming this crash is from one of my older mods using an old version of kyrptconfig crashing with the newer lib

**Comment by TheRanker** [comment]
all mods are updated to latest.. inventory sorter.. maximus diggus..  actively developed modpack.

only started happening today when updated inventory sorter.. .

any tests you perfer me to try?

**Comment by kyrptonaught** [comment]
Some of my mods haven't received updates in a bit, so by nature they are on outdated kyrptconfig libs

**Comment by kyrptonaught** [comment]
[kyrptconfig-1.3.3-1.18.zip](https://github.com/kyrptonaught/Inventory-Sorter/files/7799689/kyrptconfig-1.3.3-1.18.zip)
Can you run this with latest inventory sorter and see if it's fixed?

**Comment by TheRanker** [comment]
ssure. be 2 mins

**Comment by kyrptonaught** [comment]
If this works I will release an updated inventory sorter with this included for backwards compat

**Comment by kyrptonaught** [comment]
The technical reason for this crash: I recently reworked how I registered my keybinds and I made sure to add backwards compat with the old method to attempt to prevent exactly this. I forgot that previously in the lib specifying a default key was optional. This is proven by line 24 of your crashlog 
![image](https://user-images.githubusercontent.com/3196164/147887801-bacdd653-ac26-42f9-a9f0-01d86aa96758.png)

**Comment by TheRanker** [comment]
confirmed working with the .jar u sent :)

**Comment by kyrptonaught** [comment]
And keybinds are working properly? They can be edited in the mc controls screen and in the mods respective mod menu config? And they trigger correctly in game?

**Comment by TheRanker** [comment]
testing

**Comment by kyrptonaught** [comment]
Great, 1.8.3 was pushed to curseforge. Will be available shortly. Thank you for the help!

**Comment by TheRanker** [comment]
no problem! ty for your quick response and resoultion XD

happy dev'ing
