### ISSUE TITLE
Mod is crashing client side

### ISSUE THREAD

**Issue by ClayBC** [kyrptonaught/Inventory-Sorter#67]
Hi, after installing this mod on the client side, I am getting crashes upon launching. I've only been able to get it to work by just having it installed on the server and using the commands to sort. 

[crash-2022-01-06_13.40.21-client.txt](https://github.com/kyrptonaught/Inventory-Sorter/files/7824033/crash-2022-01-06_13.40.21-client.txt)

**Comment by kyrptonaught** [comment]
Can you update quickshulker? All of my mods make use of an internal config library, the outdated version of QS is using an outdated version of the lib that's clashing with lib provided with Inventory Sorter

**Comment by ClayBC** [comment]
That seemed to do the trick, thank you!
