### ISSUE TITLE
Sorting buttons are in incorrect location depending on window size.

### ISSUE THREAD

**Issue by NinjaPhenix** [kyrptonaught/Inventory-Sorter#7]
Sorting buttons are in incorrect location depending on window size.
Examples:
Good - Both buttons in correct location.
![image](https://user-images.githubusercontent.com/5214513/62966345-c1117380-bdfe-11e9-97b9-931bf054284d.png)
Bad - Bottom button is in the wrong location.
![image](https://user-images.githubusercontent.com/5214513/62966371-cd95cc00-bdfe-11e9-8ee6-6d76816394ff.png)
My normal resolution for playing mc - Both button are in wrong location.
![image](https://user-images.githubusercontent.com/5214513/62966405-dd151500-bdfe-11e9-8de9-9145bd4d59cf.png)

**Comment by kyrptonaught** [comment]
Thank you for the detailed report, does this take care of the issue? 
[InventorySorter-1.5.1.jar.zip](https://github.com/kyrptonaught/Inventory-Sorter/files/3498479/InventorySorter-1.5.1.jar.zip)

**Comment by NinjaPhenix** [comment]
It's better, but its still oddly placed: 
![image](https://user-images.githubusercontent.com/5214513/62970403-54e73d80-be07-11e9-90a7-1cddafc6b8e9.png)

![image](https://user-images.githubusercontent.com/5214513/62970432-60d2ff80-be07-11e9-9ba1-29d7d9b7cf9f.png)

**Comment by kyrptonaught** [comment]
I edited the comment right as you downloaded, can you redownload?

**Comment by NinjaPhenix** [comment]
Yes it's fixed now:
![image](https://user-images.githubusercontent.com/5214513/62970752-12723080-be08-11e9-9229-7e311a63ef8f.png)

**Comment by kyrptonaught** [comment]
Fixed in 1.5.1, released on curseforge
