### ISSUE TITLE
Sorting a dank with multiple oversized stacks reduces one of the stacks to 64 items

### ISSUE THREAD

**Issue by yorii** [kyrptonaught/Inventory-Sorter#73]
Using:
InventorySorter-1.8.4-1.18
dankstorage-1.18.1-3.5.4

To reproduce:
Fill a dank with two stacks of the same item, where both stacks have more than 64 items.
Press the autosort button.
One stack will retain its original size, the other stack will be reduced to 64 items.

**Comment by yorii** [comment]
Duplicate issue posted to dank storage github: https://github.com/Tfarcenim/Dank-Storage/issues/158

**Comment by kyrptonaught** [comment]
This is the proper fabric repo: 
https://github.com/Tfarcenim/DankStorageFabric

Inventory sorter does not have size 64 slots hardcoded anywhere, it uses stack.maxCount. 

They do have this listed on their curseforge page, so I'm assuming it's known that sorters don't work well with this.

WARNING: Do NOT use any other mod's autosorter(such as Inventory Tweaks) as it will not work properly with the the slots and may even delete items.  It would be a good idea to blacklist these slots in the config file.

**Comment by yorii** [comment]
Ah so it's already a well-known and documented issue I gather then, thanks for the quick reply!

**Comment by kyrptonaught** [comment]
Thank you for the report anyway!

I would like to implement a feature to have inventory sorter download a list of blacklisted inventories. To help fix issues like this. 

I'm thinking soemthing along the lines of a txt file hosted somewhere(maybe GitHub?) that just contains a blacklist. The url could be customized for pack owners to use their own. Maybe an option auto download on game launch feature too, off by default?
