### ISSUE TITLE
Sort Inventory overlapping button IntegratedTerminals Config

### ISSUE THREAD

**Issue by iKormann** [kyrptonaught/Inventory-Sorter#77]
The "MOVE MATCHING ITEMS" button of the sort inventory is covering the button to choose the click mode of the Integrated Dynamics machines, making it not possible to configure it currently.
In the image you can see that the button that should choose the click mode appears the options of the other mod.
Is there a way to configure to move these sorty inventory buttons to the side or some shortcut to disable them momentarily, thank you.

![image](https://user-images.githubusercontent.com/107667419/174230855-632a5f8d-119e-437f-bea7-60f5b1b992cc.png)
\
![image](https://user-images.githubusercontent.com/107667419/174230979-b1562094-1332-4293-b1ed-a85995a95427.png)

Sorry if the text is confusing, I used a translator.

**Comment by kyrptonaught** [comment]
Yes inventories can be blacklisted in game to disable the buttons from appearing. In the config enable, "Debug Mode", then hold shift and click on the sorting button. You should receive a prompt in chat to continue with adding the inventory to the blacklist.

**Comment by kyrptonaught** [comment]
Oh, those buttons you are talking about are not from this mod

**Comment by iKormann** [comment]
Thanks for the reply, I will try this debug mode to disable the button.
I'm using the forge version. These organize inventory buttons appear in all windows, I don't know the name of the mod to which it belongs.

**Comment by iKormann** [comment]
For anyone who has this problem:
Specific MOD: Inventory Profiles Next
Open the inventory with the problem and press the "R+G" keys and follow the instructions.
Currently I only had this problem of overlapping with the inventory of items from the Integrated Dynamics mod
