### ISSUE TITLE
Allow sorting without server-side component

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [kyrptonaught/Inventory-Sorter#8]
From what I can tell from the source, this mod will just send a packet to handle sorting on the server, making it useless on vanilla servers. Other similar mods support manually moving the items which allows them to function in multiplayer without server-side components.

If this is out of scope, perhaps some handshake can be added on server join to enable the UI buttons, so here aren't any dead buttons in the inventory screen which only serve to confuse people (like me :P).

**Comment by Cicero-Interactive** [comment]
My opinion. While I do think it might take a while to implement it, it shouldn't be very hard since Inventory Tweaks is open source and you can almost straight-up copy its code. Yeah, it's written for Forge and not Fabric, but the logic is there

**Comment by Cicero-Interactive** [comment]
Why has this been closed, @kyrptonaught?
