### ISSUE TITLE
"The game crashed whilst initializing game" 1.18.2

### ISSUE THREAD

**Issue by helixxger** [kyrptonaught/Inventory-Sorter#81]
Game crashes on 1.18.2 with inventorysorter 1.8.8

"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'inventorysorter'!
Exit-Code: -1"

_________________________________________________________________
LOG is attached

[crash-2022-07-15_15.56.38-client.txt](https://github.com/kyrptonaught/Inventory-Sorter/files/9121403/crash-2022-07-15_15.56.38-client.txt)

**Comment by kyrptonaught** [comment]
Interesting, It seems like my config library is missing. That should be included inside the mod.

Where did you download the mod? Can you try to re-download from curseforge?

**Comment by helixxger** [comment]
> Interesting, It seems like my config library is missing. That should be included inside the mod.
> 
> Where did you download the mod? Can you try to re-download from curseforge?

I already Downloaded it from Curseforge, 2 times 😅

**Comment by Maciejka1** [comment]
Do not make this issue stalled, it happended again on 1.19!

**Comment by kyrptonaught** [comment]
> Do not make this issue stalled, it happended again on 1.19!
> 
> Edit: it crashes only when optifabric mod is installed.

I believe this is a different issue. See here https://github.com/kyrptonaught/Inventory-Sorter/issues/79

There is a build released there that fixes this

**Comment by kyrptonaught** [comment]
> > Interesting, It seems like my config library is missing. That should be included inside the mod.
> > Where did you download the mod? Can you try to re-download from curseforge?
> 
> I already Downloaded it from Curseforge, 2 times 😅

Can you try to install this? This is my config lib that should be included with inventory sorting
[kyrptconfig-1.4.6-1.18.zip](https://github.com/kyrptonaught/Inventory-Sorter/files/9145250/kyrptconfig-1.4.6-1.18.zip)

**Comment by helixxger** [comment]
> > > Interesting, It seems like my config library is missing. That should be included inside the mod.
> > > Where did you download the mod? Can you try to re-download from curseforge?
> > 
> > 
> > I already Downloaded it from Curseforge, 2 times 😅
> 
> Can you try to install this? This is my config lib that should be included with inventory sorting [kyrptconfig-1.4.6-1.18.zip](https://github.com/kyrptonaught/Inventory-Sorter/files/9145250/kyrptconfig-1.4.6-1.18.zip)

It worked - i had to update fabric loader but it worked
