### ISSUE TITLE
Sorting button in incorrect position for backpacks

### ISSUE THREAD

**Issue by calloatti** [kyrptonaught/Inventory-Sorter#9]
InventorySorter-1.5.5.jar
Mpcs' Backpacks v1.1.4 - 1.14.2.jar
https://www.curseforge.com/minecraft/mc-mods/mpcs-backpacks

![image](https://user-images.githubusercontent.com/12817862/64135639-cab84680-cdc0-11e9-91ee-05de130f5de4.png)

Probably the backpacks mod is to blame.

**Comment by kyrptonaught** [comment]
The issue is definitely on their end, after some troubleshooting and digging around, it appears all the backpacks are registered with the same size inventory screen despite them all not being the same(As well as a few other odd things).
I could include a workaround if you'd like?

**Comment by kyrptonaught** [comment]
[InventorySorter-1.5.6.zip](https://github.com/kyrptonaught/Inventory-Sorter/files/3573763/InventorySorter-1.5.6.zip)

**Comment by calloatti** [comment]
Thank you! I think the real solution here is for someone to release a properly maintained backpacks mod. ;-)

**Comment by calloatti** [comment]
Seems to be working fine over here.

**Comment by magneticflux-** [comment]
@calloatti The Backpacks mod is under the GPL, be the change you wish to see in the world 😉

**Comment by kyrptonaught** [comment]
Going to contact the dev and see if I could help with the project, if not might create my own
